// Run after browser_smoke.js in the same Tabbit task, against fake_workspace.py only.
const identity=await context.request.get('http://127.0.0.1:18200/test-fixture');
const fixture=await identity.json();assert.equal(fixture.fake_models,true);assert.equal(fixture.temporary_storage,true);
const errors=[];page.on('pageerror',error=>errors.push(error.message));
const chapters=await (await context.request.get('http://127.0.0.1:18200/chapters/project/1')).json();
const chapter=chapters.data.filter(item=>item.title==='固定测试章').sort((a,b)=>b.id-a.id)[0];
assert(chapter,'Run browser_smoke.js first to create the fixture chapter');
await page.goto(`http://127.0.0.1:5175/#/projects/1/workspace?chapter_id=${chapter.id}&view=voices`);
await page.getByRole('button',{name:'03 配音',exact:true}).click();
await expect(page.getByText('雨停了吗？',{exact:true}).first()).toBeVisible();
await page.getByText('雨停了吗？',{exact:true}).first().click();
const editor=page.getByLabel('纯净朗读文本').first();
await expect(editor).toBeVisible();
await editor.fill('浏览器未保存草稿');
await page.getByRole('button',{name:'04 声音编排',exact:true}).click();
await page.getByRole('button',{name:'03 配音',exact:true}).click();
await expect(page.getByText('雨停了吗？',{exact:true}).first()).toBeVisible();
await page.getByText('雨停了吗？',{exact:true}).first().click();
await expect(page.getByLabel('纯净朗读文本').first()).toHaveValue('浏览器未保存草稿');
await page.getByRole('button',{name:'新建章节',exact:true}).click();
await expect(page.getByRole('button',{name:'留在当前章节',exact:true})).toBeVisible();
await page.getByRole('button',{name:'留在当前章节',exact:true}).click();
await expect(page.getByLabel('纯净朗读文本').first()).toHaveValue('浏览器未保存草稿');
const savePattern='**/lines/*';
let release, started;
const startedPromise=new Promise(resolve=>{started=resolve});
await page.route(savePattern,async route=>{
 if(route.request().method()!=='PUT')return route.continue();
 const response=await route.fetch();started();await new Promise(resolve=>{release=resolve});await route.fulfill({response});
});
await page.getByLabel('纯净朗读文本').first().fill('保存中的 A');
await page.getByRole('button',{name:'保存台词信息',exact:true}).first().click();
await startedPromise;
await page.getByLabel('纯净朗读文本').first().fill('稍后输入的 B');
release();
await expect(page.getByText('保存中的 A',{exact:true}).first()).toBeVisible();
await expect(page.getByLabel('纯净朗读文本').first()).toHaveValue('稍后输入的 B');
await page.unroute(savePattern);
await page.getByRole('button',{name:'新建章节',exact:true}).click();
await page.getByRole('button',{name:'放弃编辑并离开',exact:true}).click();
await expect(page.getByPlaceholder('把小说原文粘贴到这里……')).toBeVisible();
assert.deepEqual(errors,[]);
return {viewDraftRetained:true,cancelLeaveRetained:true,saveResponseKeptNewerInput:true,explicitDiscard:true,errors};
